# Generated by Django 2.0.7 on 2018-07-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('betting_end', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_addr', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nonce', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nonce', models.IntegerField(default=0)),
                ('producer_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.Producer')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.Tournament'),
        ),
    ]
