# Generated by Django 2.0.7 on 2018-07-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('multi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('summoner_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cur_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='initial_reward',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='magnification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.CharField(default='', max_length=640),
        ),
        migrations.AddField(
            model_name='team_tournament',
            name='tournament_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.Tournament'),
        ),
        migrations.AddField(
            model_name='summoner',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frame.Team'),
        ),
    ]
